site_name: Awesome Prompt Engineering
site_description: Structured, reusable prompts for ChatGPT, Claude, Gemini – focused on DevOps, scripting & infrastructure.
site_url: https://tamld.github.io/awesome-prompt-engineering/
site_author: Tam Le Duc

repo_name: tamld/awesome-prompt-engineering
repo_url: https://github.com/tamld/awesome-prompt-engineering

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
  
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - footnotes
  - md_in_html

plugins:
  - search

nav:
  - Home: index.md
  - Bash Linux: bash-linux.md
  - Devops: devops.md
  - Iac: iac.md
  - Infrastructure: infrastructure.md
  - Programming: programming.md
  - Virtualization: virtualization.md
  - Windows: windows.md
