name: Deploy MkDocs with Prompts

on:
  push:
    branches: [ main ]  # Trigger the workflow on push to main branch

permissions:
  contents: write  # Ensure the workflow has the correct permissions to push to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository to the runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Install Python 3.x

      - name: Install MkDocs and Material theme
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material  # Install MkDocs and the Material theme for MkDocs

      - name: Build Markdown docs from .prompt files
        run: |
          chmod +x build-docs.sh  # Ensure the build script is executable
          ./build-docs.sh  # Generate .md files from the .prompt files
          mkdocs build  # Build the MkDocs documentation

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force  # Deploy to GitHub Pages
